export const cardData = [
    {
        lp:1,
        icon:"",
        shortDesc:"",
        longDesc:"",
    },
    {
        lp:2,
        icon:"",
        shortDesc:"",
        longDesc:"",
    },
    {
        lp:3,
        icon:"",
        shortDesc:"",
        longDesc:"",
    },
]